// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $art from "./routes/art.tsx";
import * as $articles_slug_ from "./routes/articles/[slug].tsx";
import * as $articles_flow_field_methods from "./routes/articles/flow-field-methods.tsx";
import * as $articles_index from "./routes/articles/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $blog_code from "./islands/blog/code.tsx";
import * as $blog_flow_fields_noise_angles from "./islands/blog/flow-fields/noise-angles.tsx";
import * as $blog_flow_fields_noise from "./islands/blog/flow-fields/noise.tsx";
import * as $home_art_spinner from "./islands/home/art-spinner.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/art.tsx": $art,
    "./routes/articles/[slug].tsx": $articles_slug_,
    "./routes/articles/flow-field-methods.tsx": $articles_flow_field_methods,
    "./routes/articles/index.tsx": $articles_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/blog/code.tsx": $blog_code,
    "./islands/blog/flow-fields/noise-angles.tsx":
      $blog_flow_fields_noise_angles,
    "./islands/blog/flow-fields/noise.tsx": $blog_flow_fields_noise,
    "./islands/home/art-spinner.tsx": $home_art_spinner,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
