// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_articles_stats from "./routes/api/articles/stats.tsx";
import * as $api_wedding_list from "./routes/api/wedding/list.ts";
import * as $api_wedding_reset from "./routes/api/wedding/reset.ts";
import * as $art from "./routes/art.tsx";
import * as $articles_slug_ from "./routes/articles/[slug].tsx";
import * as $articles_adding_variety_to_flow_fields from "./routes/articles/adding-variety-to-flow-fields.tsx";
import * as $articles_flow_field_methods from "./routes/articles/flow-field-methods.tsx";
import * as $articles_index from "./routes/articles/index.tsx";
import * as $articles_stats from "./routes/articles/stats.tsx";
import * as $ask from "./routes/ask.tsx";
import * as $index from "./routes/index.tsx";
import * as $osa from "./routes/osa.tsx";
import * as $wedding_invite_ from "./routes/wedding/[invite].tsx";
import * as $wedding_guestbook from "./routes/wedding/guestbook.tsx";
import * as $wedding_index from "./routes/wedding/index.tsx";
import * as $wedding_schema from "./routes/wedding/schema.ts";
import * as $articles_code from "./islands/articles/code.tsx";
import * as $articles_flow_field_variety_vector from "./islands/articles/flow-field-variety/vector.tsx";
import * as $articles_flow_fields_methods_angle_to_point from "./islands/articles/flow-fields-methods/angle-to-point.tsx";
import * as $articles_flow_fields_methods_building_line from "./islands/articles/flow-fields-methods/building-line.tsx";
import * as $articles_flow_fields_methods_collision_detection from "./islands/articles/flow-fields-methods/collision-detection.tsx";
import * as $articles_flow_fields_methods_collision_example from "./islands/articles/flow-fields-methods/collision-example.tsx";
import * as $articles_flow_fields_methods_color from "./islands/articles/flow-fields-methods/color.tsx";
import * as $articles_flow_fields_methods_distance_to_point from "./islands/articles/flow-fields-methods/distance-to-point.tsx";
import * as $articles_flow_fields_methods_distance from "./islands/articles/flow-fields-methods/distance.tsx";
import * as $articles_flow_fields_methods_line_variation from "./islands/articles/flow-fields-methods/line-variation.tsx";
import * as $articles_flow_fields_methods_noise_angles from "./islands/articles/flow-fields-methods/noise-angles.tsx";
import * as $articles_flow_fields_methods_noise_line from "./islands/articles/flow-fields-methods/noise-line.tsx";
import * as $articles_flow_fields_methods_noise from "./islands/articles/flow-fields-methods/noise.tsx";
import * as $articles_flow_fields_methods_pointmap from "./islands/articles/flow-fields-methods/pointmap.tsx";
import * as $articles_flow_fields_methods_zooming from "./islands/articles/flow-fields-methods/zooming.tsx";
import * as $articles_illustration from "./islands/articles/illustration.tsx";
import * as $articles_useColors from "./islands/articles/useColors.ts";
import * as $articles_useResize from "./islands/articles/useResize.ts";
import * as $home_art_spinner from "./islands/home/art-spinner.tsx";
import * as $wedding_InviteFinder from "./islands/wedding/InviteFinder.tsx";
import * as $wedding_InviteForm from "./islands/wedding/InviteForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/articles/stats.tsx": $api_articles_stats,
    "./routes/api/wedding/list.ts": $api_wedding_list,
    "./routes/api/wedding/reset.ts": $api_wedding_reset,
    "./routes/art.tsx": $art,
    "./routes/articles/[slug].tsx": $articles_slug_,
    "./routes/articles/adding-variety-to-flow-fields.tsx":
      $articles_adding_variety_to_flow_fields,
    "./routes/articles/flow-field-methods.tsx": $articles_flow_field_methods,
    "./routes/articles/index.tsx": $articles_index,
    "./routes/articles/stats.tsx": $articles_stats,
    "./routes/ask.tsx": $ask,
    "./routes/index.tsx": $index,
    "./routes/osa.tsx": $osa,
    "./routes/wedding/[invite].tsx": $wedding_invite_,
    "./routes/wedding/guestbook.tsx": $wedding_guestbook,
    "./routes/wedding/index.tsx": $wedding_index,
    "./routes/wedding/schema.ts": $wedding_schema,
  },
  islands: {
    "./islands/articles/code.tsx": $articles_code,
    "./islands/articles/flow-field-variety/vector.tsx":
      $articles_flow_field_variety_vector,
    "./islands/articles/flow-fields-methods/angle-to-point.tsx":
      $articles_flow_fields_methods_angle_to_point,
    "./islands/articles/flow-fields-methods/building-line.tsx":
      $articles_flow_fields_methods_building_line,
    "./islands/articles/flow-fields-methods/collision-detection.tsx":
      $articles_flow_fields_methods_collision_detection,
    "./islands/articles/flow-fields-methods/collision-example.tsx":
      $articles_flow_fields_methods_collision_example,
    "./islands/articles/flow-fields-methods/color.tsx":
      $articles_flow_fields_methods_color,
    "./islands/articles/flow-fields-methods/distance-to-point.tsx":
      $articles_flow_fields_methods_distance_to_point,
    "./islands/articles/flow-fields-methods/distance.tsx":
      $articles_flow_fields_methods_distance,
    "./islands/articles/flow-fields-methods/line-variation.tsx":
      $articles_flow_fields_methods_line_variation,
    "./islands/articles/flow-fields-methods/noise-angles.tsx":
      $articles_flow_fields_methods_noise_angles,
    "./islands/articles/flow-fields-methods/noise-line.tsx":
      $articles_flow_fields_methods_noise_line,
    "./islands/articles/flow-fields-methods/noise.tsx":
      $articles_flow_fields_methods_noise,
    "./islands/articles/flow-fields-methods/pointmap.tsx":
      $articles_flow_fields_methods_pointmap,
    "./islands/articles/flow-fields-methods/zooming.tsx":
      $articles_flow_fields_methods_zooming,
    "./islands/articles/illustration.tsx": $articles_illustration,
    "./islands/articles/useColors.ts": $articles_useColors,
    "./islands/articles/useResize.ts": $articles_useResize,
    "./islands/home/art-spinner.tsx": $home_art_spinner,
    "./islands/wedding/InviteFinder.tsx": $wedding_InviteFinder,
    "./islands/wedding/InviteForm.tsx": $wedding_InviteForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
