// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_articles_stats from "./routes/api/articles/stats.tsx";
import * as $api_articles_trash from "./routes/api/articles/trash.tsx";
import * as $art from "./routes/art.tsx";
import * as $articles_slug_ from "./routes/articles/[slug].tsx";
import * as $articles_flow_field_methods from "./routes/articles/flow-field-methods.tsx";
import * as $articles_index from "./routes/articles/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $articles_code from "./islands/articles/code.tsx";
import * as $articles_flow_fields_angle_to_point from "./islands/articles/flow-fields/angle-to-point.tsx";
import * as $articles_flow_fields_building_line from "./islands/articles/flow-fields/building-line.tsx";
import * as $articles_flow_fields_collision_detection from "./islands/articles/flow-fields/collision-detection.tsx";
import * as $articles_flow_fields_collision_example from "./islands/articles/flow-fields/collision-example.tsx";
import * as $articles_flow_fields_color from "./islands/articles/flow-fields/color.tsx";
import * as $articles_flow_fields_distance_to_point from "./islands/articles/flow-fields/distance-to-point.tsx";
import * as $articles_flow_fields_illustration from "./islands/articles/flow-fields/illustration.tsx";
import * as $articles_flow_fields_line_variation from "./islands/articles/flow-fields/line-variation.tsx";
import * as $articles_flow_fields_noise_angles from "./islands/articles/flow-fields/noise-angles.tsx";
import * as $articles_flow_fields_noise_line from "./islands/articles/flow-fields/noise-line.tsx";
import * as $articles_flow_fields_noise from "./islands/articles/flow-fields/noise.tsx";
import * as $articles_flow_fields_pointmap from "./islands/articles/flow-fields/pointmap.tsx";
import * as $articles_flow_fields_useColors from "./islands/articles/flow-fields/useColors.ts";
import * as $articles_flow_fields_useResize from "./islands/articles/flow-fields/useResize.ts";
import * as $home_art_spinner from "./islands/home/art-spinner.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/articles/stats.tsx": $api_articles_stats,
    "./routes/api/articles/trash.tsx": $api_articles_trash,
    "./routes/art.tsx": $art,
    "./routes/articles/[slug].tsx": $articles_slug_,
    "./routes/articles/flow-field-methods.tsx": $articles_flow_field_methods,
    "./routes/articles/index.tsx": $articles_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/articles/code.tsx": $articles_code,
    "./islands/articles/flow-fields/angle-to-point.tsx":
      $articles_flow_fields_angle_to_point,
    "./islands/articles/flow-fields/building-line.tsx":
      $articles_flow_fields_building_line,
    "./islands/articles/flow-fields/collision-detection.tsx":
      $articles_flow_fields_collision_detection,
    "./islands/articles/flow-fields/collision-example.tsx":
      $articles_flow_fields_collision_example,
    "./islands/articles/flow-fields/color.tsx": $articles_flow_fields_color,
    "./islands/articles/flow-fields/distance-to-point.tsx":
      $articles_flow_fields_distance_to_point,
    "./islands/articles/flow-fields/illustration.tsx":
      $articles_flow_fields_illustration,
    "./islands/articles/flow-fields/line-variation.tsx":
      $articles_flow_fields_line_variation,
    "./islands/articles/flow-fields/noise-angles.tsx":
      $articles_flow_fields_noise_angles,
    "./islands/articles/flow-fields/noise-line.tsx":
      $articles_flow_fields_noise_line,
    "./islands/articles/flow-fields/noise.tsx": $articles_flow_fields_noise,
    "./islands/articles/flow-fields/pointmap.tsx":
      $articles_flow_fields_pointmap,
    "./islands/articles/flow-fields/useColors.ts":
      $articles_flow_fields_useColors,
    "./islands/articles/flow-fields/useResize.ts":
      $articles_flow_fields_useResize,
    "./islands/home/art-spinner.tsx": $home_art_spinner,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
